### ISSUE TITLE
Add support for CLI in geoserver-installer

### ISSUE THREAD

**Issue by gqueiroz** [brazil-data-cube/docker#1]
At least the following options should be informed in the command line:
- `--version`: The GeoServer version.
- `--disable-community-extensions`
- `--disable-all-extensions`

**Comment by M3nin0** [comment]
It may be interesting to also consider: 
- `--disable-official-extensions`

**Comment by M3nin0** [comment]
The package has been transformed into a command-line tool. Now, the user can install the package and use it from anywhere on his machine. The package deals, in addition to generating the Dockerfile files, also creating the entrypoint and tomcat configuration files in the directory where the script are being executed.

**Comment by gqueiroz** [comment]
Could you please submit a pull request with this enhancement?

**Comment by M3nin0** [comment]
Yes, pull request done
